baseurl = "/"
languageCode = "en-us"
title = "Dom Luna"
author = "Dominique Luna"
canonifyurls = true
enableEmoji = true

[params]
  author = "Dominique Luna"
  description = "Some description here"



