baseurl = "/"
languageCode = "en-us"
title = "Dom Luna"
author = "Dominique Luna"
canonifyurls = true
enableEmoji = true

[params]
  author = "Dominique Luna"
  description = "I'm a software engineer with a focus in Machine Learning and Data Visualizations."



